name: Aula da T16B
on:
  push

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World t16b
        run: echo "Hello World"

      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Instalar as dependÃªncias
        run: npm install

      - name: Executando o linter
        run: npx eslint .
